name: Sync and Modify Custom_Clash.ini for fb

on:
  push:
    branches:
      - main
    paths:
      - cfg/Custom_Clash_Full.ini # 当 Custom_Clash_Full.ini 文件更新时触发
  workflow_dispatch: # 添加手动触发事件

jobs:
  sync-and-modify:
    runs-on: ubuntu-latest
    steps:
      # Step 1: 检出源仓库
      - name: Checkout Source Repo
        uses: actions/checkout@v3

      # Step 2: 修改文件
      - name: Modify File
        run: |
          # 复制文件
          cp cfg/Custom_Clash_Full.ini cfg/Custom_Clash_Full_fb.ini

          # 在所有 "节点`url-test`" 字样 之后添加 "^(?!.*V4)"
          sed -i 's/节点`url-test`/节点`url-test`^(?!.*V4)/g' cfg/Custom_Clash_Full_fb.ini
          
          # 添加节点分组
          sed -i '/custom_proxy_group=🐟 漏网之鱼/a custom_proxy_group=🎮 游戏加速`select`(V4|V3)' cfg/Custom_Clash_Full_fb.ini
          
      # Step 3: 提交更改到仓库
      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add cfg/Custom_Clash_Full_fb.ini
          git commit -m "Update Custom_Clash_Full_fb.ini" -a || echo "No changes to commit"
          git push
